ekf_filter_node:
  ros__parameters:
    use_sim_time: false
    sensor_timeout: 0.1
    two_d_mode: true

    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_footprint"

    odom0: angle
    odom0_config: [false, false, false,
                   false, false, false,
                   true, true, true,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 10
    odom0_nodelay: false
    odom0_differential: false
    odom0_relative: false

    imu0: imu
    imu0_config: [false, false, false,
                  true, true, false,
                  false, false, false,
                  true, true, true,
                  false, false, false]
    imu0_nodelay: false
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 5

    magnetometer0: imu/mag
    magnetometer0_config: [false, false, false,
                           false, false, false,
                           false, false, false,
                           false, false, true,
                           false, false, false]
    magnetometer0_nodelay: false
    magnetometer0_relative: false
    magnetometer0_queue_size: 5
