twist_mux:
  ros__parameters:
    topics:
      navigation:  # NAV_2
        topic: /cmd_vel
        timeout: 0.5
        priority: 10
      teleoperation:  # TELEOP
        topic: /cmd_vel_teleop
        timeout: 0.5
        priority: 100